# Generated by Django 5.1 on 2024-08-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="start_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
