# Generated by Django 5.1 on 2024-08-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_alter_event_created_at_alter_event_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="capacity",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="event",
            name="type",
            field=models.CharField(default="concert", max_length=80),
        ),
    ]
